"""initial

Revision ID: 1f0618605699
Revises: 
Create Date: 2024-01-28 18:54:25.406286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0618605699'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('course',
    sa.Column('left_currency_id', sa.Integer(), nullable=False),
    sa.Column('right_currency_id', sa.Integer(), nullable=False),
    sa.Column('course', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_currency_id'], ['public.currency.id'], ),
    sa.ForeignKeyConstraint(['right_currency_id'], ['public.currency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course', schema='public')
    op.drop_table('currency', schema='public')
    # ### end Alembic commands ###
